from shared.sqladmin_.model_view.common import SimpleMV
from shared.sqladmin_.model_view.user import UserMV
from shared.sqladmin_.model_view.survey import SurveyMV
from shared.sqladmin_.model_view.question import QuestionMV
from shared.sqladmin_.model_view.survey_question import SurveyQuestionMV
from shared.sqladmin_.model_view.doctor_patient import DoctorPatientMV
from shared.sqladmin_.model_view.survey_responses import SurveyResponseMV
from shared.sqladmin_.model_view.scheduled_survey import ScheduledSurveyMV
from shared.sqladmin_.model_view.survey_reminders import SurveyReminderMV